### ISSUE TITLE
Unify echoRequestParameters and buildQueryInfoTimespan

### ISSUE THREAD

**Issue by ElJocho** [GIScience/ohsome-now-stats-service#21]
Afaik, we have two different functions doing basically the same thing; parroting start and enddate back to the user. We should unify the behavior and functions instead.

Also the behavior with how the results are given could be unified to always using the "result" key as well

**Comment by mrkhan** [comment]
The /stats endpoint needs to be as stated in [AmericanRedcross repo.](https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/API.md#statshashtag-endpoint) as its used by the existing applications

**Comment by ElJocho** [comment]
I'll leave this issue open, i think we should unify it in the future, but it needs to be discussed with HOT first :)

**Comment by ElJocho** [comment]
done, they changed their implementation to use ohsome-format
