### ISSUE TITLE
Use kebab-case or snail_case for API endpoint paths

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-now-stats-service#32]
Ideally we would also rewrite the API endpoint paths and not use CamelCase for path parts, as they are case insensitive. We should use kebap-case or snail_case instead.

**Comment by ElJocho** [comment]
-> https://github.com/GIScience/ohsome-now-stats-service/commit/0fec13316c9c36f317f74485fa01ca0133a65c64
