### ISSUE TITLE
Support queries for Topic stats

### ISSUE THREAD

**Issue by mmerdes** [GIScience/ohsome-now-stats-service#47]
## Overview

Currently, we support statistics for two 'built-in' topics, namely `building` and `road`.

The goal of this issue is to support other topics such as `place`, `healthcare` etc.

The pilot issue is `place` which is defined as follows:

```
 place IN ('country','state','region','province','district','county','municipality','city','borough','suburb','quarter','neighbourhood','town','village','hamlet','isolated_dwelling')
```

It is expected that there will be tens of topics at most, rather than hundreds.
Ideally, it should be possible to add new topics with moderate effort and risk.

## Next topics

amenities:
```
amenity=*
```

healthcare facilities:
```
(healthcare in (doctors,clinic,midwife,nurse,center,health_post,hospital) or amenity in (doctors,clinic,hospital,health_post)) 
```

## Further Topics
| topic name | impact areas | filter definition | comment |
| --- | --- | --- | --- |
| Healthcare Facilities | Public Health | `healthcare IS NOT NULL OR amenity IN ('doctors', 'dentist', 'clinic', 'hospital', 'pharmacy')` | this contains clinics, dentists, doctors, hospitals and pharmacies according to [HOT website](https://www.hotosm.org/impact-areas/public-health/). Filter definition is based on [HOT Export Tool for HDX](https://export.hotosm.org/en/v3/configurations/detail/b96a923b-8b43-437b-9dce-b4fb09530750). This is slightly different from our initial definition for healthcare facilities.  |
| Land Use Land Cover [km²] | Disasters & Climate Resilience |  `landuse=* or natural=bare_rock or natural=beach or natural=dune or natural=fell or natural=glacier or natural=grassland or natural=heath or natural=landslide or natural=mud or natural=rock or natural=sand or natural=scree or natural=scrub or natural=shingle or natural=water or natural=wetland or natural=wood or waterway=boatyard or waterway=dam or waterway=dock or waterway=riverbank` | This definition is based on [OQAPI](https://github.com/GIScience/ohsome-quality-api/blob/main/ohsome_quality_api/topics/presets.yaml#L486). There is a simpler definition by HOT Export tool, but this one is closer to  HOT Impact Areas - Data Models V1.1   |
| Social Facilities + Shelters | Disasters & Climate Resilience | `amenity in (shelter, social_facility, refugee_site) OR social_facility IS NOT NULL` | This is based on HOT Impact Areas - Data Models V1.1 |
| Education Facilities | Sustainable Cities & Communities | `amenity IN ('kindergarten', 'school', 'college', 'university') OR building IN ('kindergarten', 'school', 'college', 'university')` | this is based on the definition from [HOT Export Tool for HDX](https://export.hotosm.org/en/v3/configurations/detail/b96a923b-8b43-437b-9dce-b4fb09530750) |
|Water and Sanitation (WASH) Facilities | Disasters & Climate Resilience | `amenity in (toilets, shower, drinking_water, water_point) OR man_made in (water_tap, borehole, water_works, pumping_station, pump, wastewater_plant, storage_tank, water_well, water_tower, reservoir_covered, water_tank)` |waterways are not included here, but treated as a separate topic. This is based on HOT Impact Areas - Data Models V1.1 |
| Commercial facilities | Sustainable Cities and Communities | `shop=*` | This is based on HOT Impact Areas - Data Models V1.1 | 
| Financial Services | Sustainable Cities and Communities | `amenity in (atm, bank, money_transfer, bureau_de_change, mobile_money_agent)` | This is based on HOT Impact Areas - Data Models V1.1 |
| POIs |this is not part of an impact area, but used within HOT Tasking Manager | `amenity=* or shop=* or craft=* or office=* or leisure=* or aeroway=*` | this is based on the definition for POIs in the [old osm-stats api](https://github.com/AmericanRedCross/osm-stats-workers/blob/master/src/index.js#L1) . Maybe this topic could replace the amenities topic? |

**Comment by ElJocho** [comment]
@Hagellach37 should pharmacies or dentist be included in healthcare, and if not is the name healthcare fitting? - compare e.g. to this site where these are the most prevalent tags

**Comment by ElJocho** [comment]
@Hagellach37 railways seems to mix types that should be aggregated by count and by length
